<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>E07EC438-7B75-4437-8AA1-DA94C1E6EACC</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>name</key>
                <string>keyword.command.columbus</string>
                <key>match</key>
                <string>^\s*\b(?i)(?:AddNet|Attrib|Begin Script|CancelNet|CancelSystemRestorePoint|CD|ChangePW|ClientConfig|Copy|Delete|End Script|Error|Exit|Expand|FileSystemRedirection|Font|IniRead|IniWrite|Inventory|Load Variables|Log|MD|MSI|MSIPATCH|Path|Play|RD|Register32|Register64|RegisterFile|RegPerm|RegPerm64|RegRead|RegRead64|Rename|Replace|Return|Run|Run64|RunAs|Service|Set|SetSystemRestorePoint|SharedDLLCounter|SharedDLLCounter64|Shortcut|System|Textfile|UnRegisterFile|Wait|WallPaper|WMIRead|WMIReadList|WriteInventory)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.columbus</string>
                <key>match</key>
                <string>.(?i)/(8.3|Add|AfterEntry|Allowed|AllUsers|Append|AppendToLog|Basic|BeforeEntry|Daily|Dec|Decrypt|Default|Delete|Denied|DesktopInteractionRequired|Empty|Force|Full|IfExists |IfNotExists|Immediate|Inc|LOG|LogTypes|Machine|NoBinConvert|NoErrors|NoFileSystemRedirection|None|NoRebootOperations|OnTimeoutReboot|Reduced|Remove|Repair|Replace|ReplaceAll|RunAsAdmin|Script|Sub|Unicode|User|Volatile)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.columbus</string>
                <key>match</key>
                <string>.(?i)(AddIfMissing|AllowDuplicates|AtEnd|AtTop|CreateAnsi|CreateUnicode|DeleteLine|First|Hide|IMMEDIATE|LOGOUT|Maximize|Minimize|OmitTrailingCRLF|ONREBOOTOPERATIONS|REBOOT|REFRESH|ReplaceLine|Show|Task|WaitDown)</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.class<string>
                    </dict>

                </dict>
                <key>name</key>
                <string>keyword.command.columbus</string>
                <key>match</key>
                <string>\b(?i)(Goto)\b\s+([A-Za-z_]+)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>entity.name.class</string>
                <key>match</key>
                <string>^\s*(:)([A-Za-z_]+)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.command.columbus</string>
                <key>match</key>
                <string>\b(?i)if\s+((not)\s+)?(Installed|Group|FileVersion|File|Diskfree)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>entity.name.class</string>
                <key>match</key>
                <string>^\s*\[(?i)(header|useradd|userrepeat|userremove|clientadd|clientrepeat|clientremove|serveradd|serverrepeat|serverremove)\]</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.repeat.columbus</string>
                <key>match</key>
                <string>\b(?i)for\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.operator.columbus</string>
                <key>match</key>
                <string>\b(?:EQU|NEQ|LSS|LEQ|GTR|GEQ)\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>comment.line.rem.columbus</string>
                <key>match</key>
                <string>;($|.*$)</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.parameter.function.begin.shell</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>variable.parameter.function.columbus</string>
                <key>match</key>
                <string>(?i)(%)(~(?:f|d|p|n|x|s|a|t|z|\$[^:]*:)*)?\d</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.parameter.loop.begin.shell</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>variable.parameter.loop.columbus</string>
                <key>match</key>
                <string>(?i)(%%)(~(?:f|d|p|n|x|s|a|t|z|\$[^:]*:)*)?[a-z]</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.parsetime.begin.shell</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.parsetime.end.shell</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>variable.other.parsetime.columbus</string>
                <key>match</key>
                <string>(%)[^%]+(%)</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.delayed.begin.shell</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.delayed.end.shell</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>variable.other.delayed.columbus</string>
                <key>match</key>
                <string>(!)[^!]+(!)</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>"</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.shell</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.shell</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.double.columbus</string>
                <key>end</key>
                <string>"|$</string>
            </dict>
            <dict>
                <key>begin</key>
                <string>'</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.shell</string>
                    </dict>
                </dict>
                <key>beginCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.shell</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>string.quoted.single.columbus</string>
                <key>end</key>
                <string>'|$</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.operator.pipe.columbus</string>
                <key>match</key>
                <string>[|]</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.operator.redirect.shell</string>
                <key>match</key>
                <string>&amp;&gt;|\d*&gt;&amp;\d*|\d*(&gt;&gt;|&gt;|&lt;)|\d*&lt;&amp;|\d*&lt;&gt;</string>
            </dict>
        </array>
        <key>name</key>
        <string>Columbus File</string>
        <key>scopeName</key>
        <string>source.columbus</string>
        <key>fileTypes</key>
        <array>
            <string>wms</string>
        </array>
    </dict>
</plist>